### ISSUE TITLE
[提案] 关于 `metadata` 字段的改动建议及对 `request` 字段的初步建议

### ISSUE THREAD

**Issue by GreyElaina** [Karlatemp/mirai-websocket-api#1]
# 原来的处理方式

在本提案实施前, 与 `mirai-websocket-api`(下简称 `wsapi`) 对接的应用通过在向服务端提交数据时使用 `metadata` 字段, 借以获得相应的 `ActionResult`:

``` json5
// 请求
{
    // 其他的字段
    "metadata": "..."
}

// 服务端处理后发送
{
    // 其他的字段
    "metadata": "..." // 与请求时的一致
}
```

# 动机
当客户端上交到 `wsapi` 的数据不包括 `metadata` 时, 其获取的 `ActionResult` 没有解读的意义, 也就是说会被丢弃. 本提案旨在规范对接程序的上报数据及其对服务端所返回结果的处理方式, 使得基于其所实现的应用所潜在的问题得到一定程度上的解决.

# 具体实现要求

若客户端请求一 **可能得到回应(Response)** 的接口, 则要求在请求中包含一必须存在的 `request` 字段, 该字段所对应的值为一 `Map<String, Any>` 对象(暂定), 并在其中包含一 `id` 字段, 其类型为 `String`. 无论如何, 服务端必须回应客户端一个 `Response` 而非 `ActionResult`, 其包含一 `response` 字段, 且该字段中有且仅有字段 `requestId`(类型为 `String`, 内容为在请求中所包含的 `request.id` 字段) 及本提案之后在其他提案中所添加的字段:

``` json5
// request
{
    "request": {
        "id": "..."
    }
}

// response
{
    "response": {
        "requestId": "..."
    }
}
```

# 细节

 - `Response` 可以不在实际实现中出现, 这里仅用来说明;
 - 请求中的字段 `request` 与 `Response` 中的 `response` 面向其他提案开放扩展;

**Comment by Karlatemp** [comment]
修改 Response 需要同时考虑event的广播

**Comment by GreyElaina** [comment]
> 修改 Response 需要同时考虑event的广播

我在提案中说明了, 此处出现的 `Response` 仅用作说明, 你可以理解为 `ActionResult` 而不是一般形式的 `Response`.

**Comment by Karlatemp** [comment]
修改 `ActionResult` 的序列化方式会影响各类 `Event` 的广播, 必须一起重新设计

以下是对此提案的一些修改
```json5
// event
{
  "type": "Event",
  "event": {
      //.....
  }
}

// action result
{
  "type": "ActionResult",
  "id": "",
  "result": {
    "success": false,
    "simpleError": "",
    "fullError": "",
    "content": [JSON OBJECT]/null
  }
}

// request
{
  "type": "REQUEST TYPE",
  "requestId": "",
  "content": {}
}
```

**Comment by GreyElaina** [comment]
不是很推荐在 `json` 中使用 kebab-case 命名值, 这会使客户端处理这边增加成本...  
改为这样如何?既易于阅读又便于处理

```
// kekab-case, 任何情况下都不推荐在 json 中使用....
action-result

//  小骆峰, 建议用于命名字段
requestId

// 大骆峰, 建议用在 `type` 字段.
ActionResult

// 不推荐使用的匈牙利命名法...
msg(Message)
```

**Comment by GreyElaina** [comment]
就这样吧, 在 json 中让不受信任的客户端包含任意信息总让我觉得没有安全感.
