### ISSUE TITLE
[求助]发送闪照出现错误

### ISSUE THREAD

**Issue by lindongbin** [Karlatemp/mirai-websocket-api#3]
发送的格式内容
{'type': 'SendToGroup', 'content': {'bot': 1077729254, 'group': 2880722, 'message': [{'type': 'FlashImage', 'image': {'type': 'Image', 'url': 'https://bkimg.cdn.bcebos.com/pic/562c11dfa9ec8a13632798e0e049868fa0ec08fa6ad2'}}]}}

出现的错误提示
{"type":"ActionResult","success":false,"result":{"error":"kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 223: Expected \'}\'\\nJSON input: .....32798e0e049868fa0ec08fa6ad2\\"}}]}}","errorDetail":"kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 223: Expected \'}\'\\nJSON input: .....32798e0e049868fa0ec08fa6ad2\\"}}]}}\\r\\n\\tat kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:30)\\r\\n\\tat kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:329)\\r\\n\\tat kotlinx.serialization.json.internal.StreamingJsonDecoder.endStructure(StreamingJsonDecoder.kt:62)\\r\\n\\tat io.github.karlatemp.miraiwebsocketapi.actions.Request$RequestSerializer.deserialize(Request.kt:102)\\r\\n\\tat io.github.karlatemp.miraiwebsocketapi.actions.Request$RequestSerializer.deserialize(Request.kt:26)\\r\\n\\tat kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:62)\\r\\n\\tat kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:40)\\r\\n\\tat kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)\\r\\n\\tat io.github.karlatemp.miraiwebsocketapi.MiraiWebsocketApiKt$web$1$1.invokeSuspend(MiraiWebsocketApi.kt:222)\\r\\n\\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\\r\\n\\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)\\r\\n\\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)\\r\\n\\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)\\r\\n\\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)\\r\\n\\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)\\r\\n"}}

用的是 2.0.0 dev 2，麻烦看下是哪里出问题了

**Comment by Karlatemp** [comment]
```json
{
    "type": "SendToGroup",
    "content": {
        "bot": 1077729254,
        "group": 2880722,
        "message": [
            {
                "type": "FlashImage",
                "image": {
                    "url": "https://bkimg.cdn.bcebos.com/pic/562c11dfa9ec8a13632798e0e049868fa0ec08fa6ad2"
                }
            }
        ]
    }
}
```
FlashImage#image删除type字段即可
